new t

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,14 +1,9 @@
 #!/usr/bin/env bash
 #  script to reload Gunicorn in a graceful way.
 
-# Find the Gunicorn master process ID
-GUNICORN_PID=$(ps -e -o ppid= | sort -u | grep -v '0' | xargs -I {} ps -p {} -o pid,cmd | grep 'gunicorn'| awk '{print $1}')
-
-if [ -z "$GUNICORN_PID" ]; then
-  echo "Gunicorn master process not found." && exit 1
+# Send the SIGHUP signal to the Gunicorn master process to gracefully reload
+if sudo ps aux | grep gunicorn | grep -v 'grep' | awk '{ print $2 }' | xargs kill -HUP; then
+echo "Gunicorn reloaded successfully."
+else
+echo "Failed to reload Gunicorn." && exit 1
 fi
-
-for pidd in $GUNICORN_PID; do
-    # Send the SIGHUP signal to the Gunicorn master process to gracefully reload
-    kill -HUP "$pidd";
-done
